### GET ALL USERS
GET http://localhost:5000/users

### GET USER BY ID
GET http://localhost:5000/users/3

### POST USER
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "tes",
    "email": "tes@tes.com",
    "gender": "Male",
    "password": "12345678"
}

### EDIT USER
PUT http://localhost:5000/users/3
Content-Type: application/json

{
    "name": "tessss",
    "email": "tesss@tessss.com",
    "gender": "Male",
    "password": "123456"
}

### DELETE USER
DELETE http://localhost:5000/users/2