### GET ALL USERS
GET http://localhost:5000/users

### GET USER BY ID
GET http://localhost:5000/users/1

### POST USER
POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "tes",
    "email": "tes@tes.com",
    "gender": "Male"
}

### EDIT USER
PUT http://localhost:5000/users/14
Content-Type: application/json

{
    "name": "tessss",
    "email": "tesss@tessss.com",
    "gender": "Male"
}

### DELETE USER
DELETE http://localhost:5000/users/891