### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "tesss@tessss.com",
    "password": "123456"
}

### LOGOUT (Ganti refresh_token dengan refresh token yg sesuai)
DELETE http://localhost:5000/logout
Cookie: refreshToken=refresh_token

### GET ACCESS TOKEN (Ganti refresh_token dengan refresh token yg sesuai)
GET http://localhost:5000/token
Cookie: refreshToken=refresh_token

### GET ALL USERS
GET http://localhost:5000/users
Authorization: "Bearer access_token"

### GET USER BY ID
GET http://localhost:5000/users/3
Authorization: "Bearer access_token"

### POST USER
POST http://localhost:5000/users 
Authorization: "Bearer access_token"
Content-Type: application/json

{
    "name": "tes",
    "email": "tes@tes.com",
    "gender": "Male",
    "password": "12345678"
}

### EDIT USER
PUT http://localhost:5000/users/3
Authorization: "Bearer access_token"
Content-Type: application/json

{
    "name": "tessss",
    "email": "tesss@tessss.com",
    "gender": "Male",
    "password": "123456"
}

### DELETE USER
DELETE http://localhost:5000/users/2
Authorization: "Bearer access_token"